### PR TITLE
creating cli_executable file and adding it to gh releases automatically

### PR DESCRIPTION
**Pull request by tnrich**
Connects https://github.com/TeselaGen/fsml.org/issues/58

### CODE REVIEW

**Review by tgadam — CHANGES_REQUESTED** [review]
This doesn't appear to work on an Intel Mac

image

image

**Comment by tnrich** [comment]
@tgadam can you try this again when this PR action finishes building? I think I had the m1 and intel builds swapped :)

**Comment by tgadam** [comment]
So I got it to work but not without jumping through a bunch of security hoops. @tnrich did I hear recently that you got Mike to setup an Apple Developer account?

**Comment by tnrich** [comment]
@tgadam yes I have a functional apple developer account I believe.

**Comment by tgadam** [comment]
@tnrich we should be able to use that account to sign the mac executables to prevent the security headaches

**Pull request closed without merging**
